extraction:
  java:
    index:
      build_command: "mvn clean package -B -V -e -Dfindbugs.skip -Dcheckstyle.skip \
        \ -Dpmd.skip=true -Denforcer.skip -Dmaven.javadoc.skip -DskipTests -Dmaven.test.skip.exec \
        \ -Dlicense.skip=true -Drat.skip=true -Ppublic"
      java_version: "8"
